name: Aravis-macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Unbreak Python in Github Actions
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
        sudo rm -rf /Library/Frameworks/Python.framework/
        brew install --force python3 && brew unlink python3 && brew unlink python3 && brew link --overwrite python3
    - name: Install dependencies
      run: |
        brew update
        brew install meson ninja gcc gettext intltool libxml2 libusb gstreamer gnome-icon-theme gobject-introspection glib
    - name: Build
      run: |
        meson --buildtype=plain -Ddocumentation=disabled -Dgst-plugin=enabled -Dintrospection=disabled -Dusb=enabled -Dviewer=enabled . ./build
        ninja -C ./build
      env:
        CC: gcc
    - name: Tests
      run: meson test -C build/ -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt
    - name: Collect Artifacts and Dependencies
      if: success()
      run: |
        echo "::group::meson install"
        meson install -C ./build --destdir $(pwd)/install
        echo "::endgroup::"
        echo "::group::brew install"
        brew install dylibbundler
        echo "::endgroup::"
        mkdir dist
        dylibbundler -od -b -x ./install/usr/local/lib/libaravis-0.8.dylib -d ./dist -p @loader_path/
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: macos_aravis_build
        path: |
          build/
          install/
          dist/
